sudo: required
language: node_js
node_js: "8"
install:
  - npm install hexo-cli -g
  - npm install
before_script:
  - sed -i "" "s/LEANCLOUD_COUNTER_APP_ID/$LEANCLOUD_COUNTER_APP_ID/g" ./_config.yml
  - sed -i "" "s/LEANCLOUD_COUNTER_APP_KEY/$LEANCLOUD_COUNTER_APP_KEY/g" ./_config.yml
  - sed -i "" "s/LEANCLOUD_COUNTER_USER_NAME/$LEANCLOUD_COUNTER_USER_NAME/g" ./_config.yml
  - sed -i "" "s/LEANCLOUD_COUNTER_PASSWORD/$LEANCLOUD_COUNTER_PASSWORD/g" ./_config.yml # 博客配置，LeadCloud 计数器
  - sed -i "" "s/LEANCLOUD_COUNTER_APP_ID/$LEANCLOUD_COUNTER_APP_ID/g" ./source/_data/next.yml
  - sed -i "" "s/LEANCLOUD_COUNTER_APP_KEY/$LEANCLOUD_COUNTER_APP_KEY/g" ./source/_data/next.yml # 主题配置，LeadCloud 计数器
script:
  - hexo g -d
addons:
  ssh_known_hosts: 120.77.38.74
before_deploy:
  - openssl aes-256-cbc -K $encrypted_c0dfcad89005_key -iv $encrypted_c0dfcad89005_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/public/* $DEPLOY_USER@120.77.38.74:$DEPLOY_PATH
  on:
    branch: master